language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.1'
  - '7.2'
  - '7.3'
env:
  - LARAVEL=5.5
  - LARAVEL=5.6
  - LARAVEL=5.7
  - LARAVEL=5.8
  - LARAVEL=6.0
  - LARAVEL=6.5

matrix:
  exclude:
    - php: '7.1'
      env: 'LARAVEL=6.0'
    - php: '7.1'
      env: 'LARAVEL=6.5'

script:
  - vendor/bin/phpunit

before_install:
  - MINOR=`echo $LARAVEL | sed 's/[5|6]\.\([0-9]\+\)/\1/'`
  - '[[ $LARAVEL =~ ^6\.[0-9]$ ]] && MAJOR=6 || MAJOR=5'
  - '[ 6 -eq $MAJOR ] && ORCH=4 || ORCH=3'
  - composer require "illuminate/support:${MAJOR}.${MINOR}.*" --no-update -v
  - composer require "illuminate/console:${MAJOR}.${MINOR}.*" --no-update -v

install: composer install --no-interaction

notifications:
  email: false
  slack:
    secure: "KR5WTObwaHBKES1i8Hy6+lEwrysw5Km4VNlLxiGSXUWc3Agg8LbdKqEb7ADQ+LNbFAapd98BX0jb5VDJ28VNIjTyMqeJp1xpGPq9NOG5B/dxV8F4qX/HyGAh9yz66EfVY+/AVGqeNubus9PnSSHCHGrOGi+39qUNfsl7D33qPAGkQ/+MHvmFhCI4IwNZY4BRduKZyYoIeRRe1KiCEdBquLl9BwP17JlWIkrpEXq0qwYSLHRqiMGNWvg7ap2QjFERu03Haroh5KgtZzLxIuyMfSLYKc84KJEjX6taac0qCLHoBMxdyyQnLOtfRhIb2R6ITZoSzX27qQfsvkKG2USNkbasTiefB8Oa73yJryycr4V6U9z0mU6zOn5rPGFVD5IiqVh/wfYzSC5wgChNP2l7c/l4vsEzgKW2Gm9PMX9KVRan6c9HEzwF7Wn5IHQYr/xWlbNtoQ1n1kQUz/gs0xt3YcwJLMemUvJTALqMgbPmu9P1kkD/2msZsbwwnBk4qZslAkoWhfNnWb2XesLEBU+gwYUqLPSO4tQA78cOtyl2nzJ0nVNdMPxUljgFNkX7dm9BTVbWuNjB9NcmC/aAKUGICdtfHFxfS4Yswewg7RZEkDpYxkB3rusVFdJgG4j2m+egb9w3b4e22xgYt1OF8tspexEzFjC67S+73rY1rmwkAiU="
