language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.3'
  - '7.4'

env:
  - LARAVEL=6.0
  - LARAVEL=6.20
  - LARAVEL=7.0
  - LARAVEL=7.29
  - LARAVEL=8.0
  - LARAVEL=8.15

script:
  - vendor/bin/phpunit

before_install:
  - MINOR=`echo $LARAVEL | sed 's/[6|7|8]\.\([0-9]\+\)/\1/'`
  - '[[ $LARAVEL =~ ^7\.[0-9]+$ ]] && MAJOR=7 || MAJOR=6'
  - '[[ $LARAVEL =~ ^8\.[0-9]+$ ]] && MAJOR=8 || true'
  - echo "Testing against Laravel ${MAJOR}.${MINOR}"
  - composer require "illuminate/support:${MAJOR}.${MINOR}.*" --no-update -v
  - composer require "illuminate/console:${MAJOR}.${MINOR}.*" --no-update -v

install: export COMPOSER_MEMORY_LIMIT=-1 && composer install --no-interaction

notifications:
  email: false
  slack:
    secure: IqFfrIq4Dss1bj3prmKPH8zmS8eY4c+zKgQSQbDg/3ltO2hzt167KgCZ+vp61opssjstWh11v3uffcF/UK0d2R8VQWl0K57afCm5rsreUk2uojnkiSDMcZBqwP808e3rVaWvLcZfThXKxaqaZ6S7S2MGhXM6vgbg+Vr/dXQoHGEbt3jPJqdHWipEAQxRszmtgHaBkU1lrlhKmxE8RyiAIPXlSMORhFV8ZV9Ikb9vljGJO9eGGgiFWUDzxzAGfwoP5Ju5AAOBbPn8OM/dezdktubiydWcjvnoZLo9fSwKt8grIZaZ4cxvAq4ganXMEIQH1a6jFJ+RFjd2mpM8zd8LutR1TvmX6Zsp2eye4P7ecmAGqmTzghe6bHrPCfZ925UAEB5SBqYT9tZGHMWnDvg5Rnc9UD50PQrx+0zWh5b2qhpR7C12cxTVM3GrmznN6+ErYntG+ga/9efoAfWm7AAaAJSY76bhMhWhJWB9TRgn0y8aodQemrkX0cfF/RBpCzI2wxLmftKqdZ9zY1nzuMevZPz9LOddpnFvT6Z+s/ifpaQSykcx9L28ApyAljjwQ9NvAhZbbjueKIDu2WiTm6sDlIshke9oZ34nvoy7d6FZGUZtO6yfd4y+jAxnJIxCRKr26l8+THOAqzNA9YKY6yQNdhph9uevT9BcdGmBa2FunII=
