language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.2'
  - '7.3'
  - '7.4'

env:
  - LARAVEL=5.5
  - LARAVEL=5.6
  - LARAVEL=5.7
  - LARAVEL=5.8
  - LARAVEL=6.0
  - LARAVEL=6.8

script:
  - vendor/bin/phpunit

before_install:
  - MINOR=`echo $LARAVEL | sed 's/[5|6]\.\([0-9]\+\)/\1/'`
  - '[[ $LARAVEL =~ ^6\.[0-9]$ ]] && MAJOR=6 || MAJOR=5'
  - composer require "illuminate/support:${MAJOR}.${MINOR}.*" --no-update -v
  - composer require "illuminate/console:${MAJOR}.${MINOR}.*" --no-update -v

install: composer install --no-interaction

notifications:
  email: false
  slack:
    secure: "nFbdOCJprQXv+d5Lgu5PRNJhfwlcOGM2ore5VOzYvv/q7oDBrHx7e5iiOCB2mFV8ac5cqq8PJEmiHfyOW0tCsMXNMbNqItf8jmqnjI1Ve67N+yfhCZSAsglRxavhA8fsWO9Fc4+1BxfetaF5oovj/NP/busuUwx8/ohwHqTDeKbXdxiNnPFtv64vmoU+V9pPqPQOyk9aWnoPqIyIyy0tAQaWAcgcijKqp5t7ydkSmvhbzT/Yrhj3i0Tj6uTKSuaXHX42/aYv9wxsZ5gU1xEwda3hdtl3RB6p3tbDCTavC9bmqX/Qq/VVszRtsyrwlvFFLAeY5OdVl4DxydGpKZ6gVmDWTXFrlRAufB2zACWAyBqK98lVI7cywaMfnZ33lpeaGGbQ7wWAvM/56ZwXu1PmtT4gRPlD05jS/Ps7E9K5sDs99Jms+sl61htivuSILP9yIMxUIMCFodNgccAWMia8qDiFIumsjIL0HKQz7vxd2GWj4d0IrBDL+3daE0r9pVokASN30mVR/FSVRE/SELMl7uPkfH+4qj75FEtSsWOx4ijHGva0rU+NoI71osqIy0ayz/htEPlPCzQ00kkJeO1qFfLi8x95Xnes2xtuXv8S1U+m9thlU++0SCSMW0/IQJAzpNrA2cgQ41YznOtV6X8WPQKnHTbEm+fid0Y3l7lhwkI="
