language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.3'
  - '7.4'
  - 'nightly'

env:
  - LARAVEL=6.0
  - LARAVEL=6.20
  - LARAVEL=7.0
  - LARAVEL=7.29
  - LARAVEL=8.0
  - LARAVEL=8.16

matrix:
  exclude:
    - php: 'nightly'
      env: 'LARAVEL=6.0'
    - php: 'nightly'
      env: 'LARAVEL=7.0'
    - php: 'nightly'
      env: 'LARAVEL=8.0'

script:
  - vendor/bin/phpunit

before_install:
  - MINOR=`echo $LARAVEL | sed 's/[6|7|8]\.\([0-9]\+\)/\1/'`
  - '[[ $LARAVEL =~ ^7\.[0-9]+$ ]] && MAJOR=7 || MAJOR=6'
  - '[[ $LARAVEL =~ ^8\.[0-9]+$ ]] && MAJOR=8 || true'
  - echo "Testing against Laravel ${MAJOR}.${MINOR}"
  - composer require "illuminate/support:${MAJOR}.${MINOR}.*" --no-update -v
  - composer require "illuminate/console:${MAJOR}.${MINOR}.*" --no-update -v

install: composer install --no-interaction

notifications:
  email: false
  slack:
    secure: "Q7HuqoF4DMi2cZmnVzLRfGhIQIPAyY1+bXZGngnaEkNDsSm1khvkOcRIuiBIWS+yJEY0AIZunRTq3R4DvMFW9DQWvlFzYKF3duQVKBfZdN+hoN2GU2rkoUqnwvAlYivtt0VE066QcZ3ScHk35Q4pWHMNK4xtE+UY7Tgk2+MLL4hZ1ePM8LClck+S3jHH4tGMRzkKu0I+ht+BscdSQ1kMnbQH47p8w1zaXpMsBAFUHKmLNm65irS+cfDY5eicnOvAwuRjGxC6KaWzvoTDtxpLNzDk12D1rGN+0y3eFPHu8Rnb3VXLkTMxaWbqlnfqfrHvzkxCAmYCh36d10VLPih9oV+057c9lW9NCVxQkAatVo083YWpcrrHvTrdU9hdUaUhVFhPyLqgr9RyDMUk4uHcJzLGIgebx8pezUXiaY8TFvmFHPG/Krginjv38L47Gs+zWDPeSmyI+Z6HD8jB6/ypcHIVvOscjDGTklDqnuWx3rfno92wyUAly/rqA/AuiGAOcvBfN3uEet81pyFhb8d2Qi2bQAQxsdVjHi2IiR4K6IDuMUoS038PuateMiMGepuGMywheXFLuxE2c3Ymb0ekL3Jj26gfRagFXPyC22C/o+qy2z8k/l0MhEbIvWm22eZU1bHIZqgQUQwcf+G+19+CdKbf8Ie5Gz2NYAwBIl/WAuw="
