language: php

cache:
  directories:
  - "$HOME/.composer/cache"

php:
  - '7.3'
  - '7.4'
  - '8.0'

env:
  - LARAVEL=6.0 TEST_DB_ENGINE=sqlite
  - LARAVEL=6.20 TEST_DB_ENGINE=pgsql
  - LARAVEL=6.20 TEST_DB_ENGINE=mysql
  - LARAVEL=6.20 TEST_DB_ENGINE=sqlite
  - LARAVEL=7.0 TEST_DB_ENGINE=sqlite
  - LARAVEL=7.30 TEST_DB_ENGINE=pgsql
  - LARAVEL=7.30 TEST_DB_ENGINE=mysql
  - LARAVEL=7.30 TEST_DB_ENGINE=sqlite
  - LARAVEL=8.0 TEST_DB_ENGINE=sqlite
  - LARAVEL=8.17 TEST_DB_ENGINE=sqlite
  - LARAVEL=8.17 TEST_DB_ENGINE=pgsql
  - LARAVEL=8.17 TEST_DB_ENGINE=mysql

matrix:
  exclude:
    - php: '8.0'
      env: 'LARAVEL=6.0'
    - php: '8.0'
      env: 'LARAVEL=7.0'
    - php: '8.0'
      env: 'LARAVEL=8.0'

script:
  - vendor/bin/phpunit --testdox

before_install:
  - MINOR=`echo $LARAVEL | sed 's/[6|7|8]\.\([0-9]\+\)/\1/'`
  - '[[ $LARAVEL =~ ^7\.[0-9]+$ ]] && MAJOR=7 || MAJOR=6'
  - '[[ $LARAVEL =~ ^8\.[0-9]+$ ]] && MAJOR=8 || true'
  - echo "Testing against Laravel ${MAJOR}.${MINOR}"
  - composer require "illuminate/support:${MAJOR}.${MINOR}.*" --no-update -v
  - composer require "illuminate/console:${MAJOR}.${MINOR}.*" --no-update -v
  - sh -c "[ ! -z $TEST_DB_ENGINE ] && [ 'mysql' = $TEST_DB_ENGINE ] && mysql -e 'DROP DATABASE IF EXISTS order_test;CREATE DATABASE order_test;'" || true
  - sh -c "[ ! -z $TEST_DB_ENGINE ] && [ 'pgsql' = $TEST_DB_ENGINE ] && psql -c 'create database order_test;' -U postgres" || true

install: composer install --no-interaction

services:
  - mysql
  - postgresql

notifications:
  email: false
  slack:
    secure: vNQZI+ZLjfMwhak4wAKAC3BXOhs2Auea35GsPF0fXON0VedHVJ48NKYeMp98cBwe5BXV2TKH5ArZTrxCcXjeOdJXtls2J1WnbawpRbtBUQCu10sudvboVZNGe1IZVGqV1+YpVKAg8t3/Ur6QqDQAmLhlCb61i4e+cSpQcUdo8xRH7fJ4aud8RdFUXDlL9pdct+nJdlkyp8NUffzjU+rSYtWj52ilETUg/8kAQeA9PrYOHaf4kOvg7P0CNNTaQWkMuxM9p7x/jMfrU0/VFLTZJkszzQ0sQRC4EESgvdhSzvvvr3qNQ3dtLU1RVRXhpdNT17OBqwR2jkApKwUkJdtMwwygkVXH51nfgHcEjdfVLVZihc27u25w7OCXCIX9Z47skMAEk/m592qgsJVmlpeZCNKQZux6pqFVF/GBbgiTRYrRNYEpsHz/lBPaJdy+VsUe+xLeYQKFor4jLjCNwfwym7SuXKV5TOVcdGoCUD+l8j8gO1rHbwONdylSK67ZOzynHxg0hgONI1VtUK6o3MDhd7IG5mMnBgVMIbdnEL27KAS68PJswcc4uhc7V1g2B/mTzgwV4Pobk52kw4cXUyqMVk2QdD5ofssI78t+BflnEavV+F9yrEhybXyvYiZpkkv7zdLjU+4IBSALxNu7yy+fp5EK1KTaMcflUHGdQxffZpY=
