language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.2'
  - '7.3'
  - '7.4'

env:
  - LARAVEL=5.5
  - LARAVEL=5.6
  - LARAVEL=5.7
  - LARAVEL=5.8
  - LARAVEL=6.0
  - LARAVEL=6.8

script:
  - vendor/bin/phpunit

before_install:
  - pecl install decimal
  - MINOR=`echo $LARAVEL | sed 's/[5|6]\.\([0-9]\+\)/\1/'`
  - '[[ $LARAVEL =~ ^6\.[0-9]$ ]] && MAJOR=6 || MAJOR=5'
  - composer require "illuminate/support:${MAJOR}.${MINOR}.*" --no-update -v
  - composer require "illuminate/console:${MAJOR}.${MINOR}.*" --no-update -v

install: composer install --no-interaction

notifications:
  email: false
  slack:
    secure: "GzDUSnBAV4W5ZoQhqlbF0E7tcz9I59Dx2QVX5uDn8OldaPh4+VvGuNQeqUgHLSebiNQn80qqUuQwdDNQZEF9XzJ3w40RMCb9srDSly+YTV5vVz5WFIt+Shl7wFA45dmbrGNvFLq+dwPw9qv/HlVKvrp3KBrdkfIQrxzvrFG9rdGfWlG3CzUUuK84CKSdT4+FGLeZIuXKR3HcH7lXPEfiF+s7o6qmja7dx4/5UAq5r48JYNFHDaesytCDkmOXPDP3ZRtTyr4wA0hHh1BC39J4bb0wF9PE8Hg9VN4jtO1ExizKyrQgt50nF7vWUB/S71GKMxgckrFXOUyFTuuF6g2Kd4+To9XNcd7Lmit1k89iB/8mRkt1M0wJ2ak+JPlZAnb5pHhgzajV7y94Xx/WR+j8t9TsgLOLJfSC8z0HQ+10UocJEVfqW0T6O7BCTtxti31RU6XZNIYDGtPWLD7WSX6bajiY0TRFU9pdMDAB+dLbN+dLnNguJBJ+06FDJIUXAET93nCoOOOvvRTyAZRxdPZrmFS/HlHnHF55aeUR/aHl1c6qWaR6rFNv+rccx64+wKsgFn0F5gpbumanU33QcacvAcI5ZpbXqVh37t3l92YB7jEiI26dDR2ovNvCTK1ow20abs+ikl0Qaa707pcGET3rXeYLR3rPfi3cjxN64TTjq08="
