language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.4'

env:
  - LARAVEL=6.19
  - LARAVEL=7.0
  - LARAVEL=7.28
  - LARAVEL=8.0
  - LARAVEL=8.12

script:
  - vendor/bin/phpunit

before_install:
  - composer self-update --2
  - MINOR=`echo $LARAVEL | sed 's/[6|7|8]\.\([0-9]\+\)/\1/'`
  - '[[ $LARAVEL =~ ^7\.[0-9]+$ ]] && MAJOR=7 || MAJOR=6'
  - '[[ $LARAVEL =~ ^8\.[0-9]+$ ]] && MAJOR=8 || true'
  - echo "Testing against Laravel ${MAJOR}.${MINOR}"
  - composer require "illuminate/support:${MAJOR}.${MINOR}.*" --no-update -v
  - composer require "illuminate/console:${MAJOR}.${MINOR}.*" --no-update -v

install: composer install --no-interaction

notifications:
  email: false
  slack:
    secure: eDAHXak13Utq5XPHnIFRfdIyqIPTPC6Vawn+v+/ltP7Jv8/DdjhGRLCc02dJOc3TkPbCNZEfs2r2gJLw87NQeaOAkerkQMUi3/EaScv1QY/NKWiq/sbOgOb8BLZN9D9bIv3BNn4gthZqh/7cJUYnpHane5H0h8Bsqf530VoD/0oUBC28ZbuNPw9HdSDXj73AtWYUawBhREDzQzvpFRtHjh10yJPHzvluVnusisNzhS/aCG1kfH449j8oxjnnh20fChkySXSSiz5tjOGHZVpHIvgTusljK3+4PAfZXGs40CaZ7PjF7I8ASaDNmgO+J6hlhM8bcR+LkWLTcsi56Mwiyl+NnXgBqX/8wl+CHbO4Njd3eZ+WypEDJmyj8dRfbxlQ9A5LbfnBavtEorPMLUTKkVzu13iljBDXM5cmStP8f6vwG2/se+g9wgwW6FNh8kwXtjiTMrY5Xc20Zy0IUXwQY4WwRq/8QgGf2DRkHqa+ZaOGmMQHGGrtKD7TATTCBMFDg4fC60Dt0nsYtPX/t/+9H5PGHjKWoJMX42wayNJrV6ktfOnX/ZBXhhCYrr4XVfphO4LSEBe6kUonTgOWSOJPmwswjctPnuAobEKH7ZAGaEiF6rCpgisJ13mOsOU0HkMFWbXJj+HnMGPGprNnmPb/t0F7sZZ3AjXy9gnSi903Of8=
